lizlevine/kick-covid-19

frontend/kick-covid-19/src/App.js
frontend/kick-covid-19/src/components/NavBar.js

Pushing up because prettier is broken, and I cannot track changes because of it. I just made minor changes to the NavBar.

Homepage style

---

controllers/answer.controllers.js
controllers/post.contollers.js
controllers/user.controllers.js
models/answer.models.js
models/index.js
models/post.models.js
models/user.models.js
routes/api/answer.routes.js
routes/api/index.js
routes/api/post.routes.js
routes/api/user.routes.js
routes/index.js
utils/crudControllers.js

* TESTING PHASE FOR ROUTES / CRUD OPERATIONS ON POSTMAN *
*DONT MERGE, UNTIL CONFIRMED TO WORK*

feat: Built routes, controllers / TESTING ON POSTMAN

---

frontend/kick-covid-19/package-lock.json
frontend/kick-covid-19/package.json
frontend/kick-covid-19/src/App.css
frontend/kick-covid-19/src/App.js
frontend/kick-covid-19/src/components/About.js
frontend/kick-covid-19/src/components/Contact.js
frontend/kick-covid-19/src/components/Header.js
frontend/kick-covid-19/src/components/Home.js
frontend/kick-covid-19/src/index.js

Frontend has templating functionality setup, with the Navbar staying and pages changing. Very preliminary, will continue to style and add more functionality.

feat: folder structure synced up with page changes in react app.js

---

controllers/auth.controllers.js
controllers/post.contollers.js
controllers/user.controllers.js
models/user.models.js
package-lock.json
package.json
routes/auth.routes.js
routes/index.js
server.js
utils/auth.js

added npm package as well as changing scripts to accommodate m-lab provision to build app in Heroku.

Added npm concurrent

---

controllers/answer.controllers.js
controllers/post.contollers.js
controllers/user.controllers.js
models/answer.models.js
models/user.models.js
package-lock.json
package.json

**User Authentication**
Done:
User Model
WIP:
Auth Controller
Auth Utils
Auth React

WIP: Building User Auth

---

frontend/kick-covid-19/package-lock.json
frontend/kick-covid-19/package.json
frontend/kick-covid-19/src/components/Blog.js
frontend/kick-covid-19/src/components/Post.js

Added a blog post component and started setting up the blog to append blog posts only from local server. Currently troubleshooting.

Blog functionality

---

frontend/kick-covid-19/package.json
frontend/kick-covid-19/src/components/Blog.js
frontend/kick-covid-19/src/components/Post.js

Blog posts appending with local API route data. Need to stylize.

feat: blog working

---

frontend/kick-covid-19/src/App.js
frontend/kick-covid-19/src/components/Post.js
frontend/kick-covid-19/src/pages/Blog.js
frontend/kick-covid-19/src/pages/Posts.js

Making PR to have reviewed
As of now can only grab post ID and render in single list view, next branch will fix that functionality.
Will do this by making a request for specific body of post using id from url.

Singlepost view

---

frontend/kick-covid-19/src/pages/Blog.js
frontend/kick-covid-19/src/pages/Posts.js

Pushing up PR for review and tracking purposes. With this PR, hoping to have the ability to see a single post in its own page. Will be able to comment on it and accept answer in the future.

feat: appending post by id to single view page

---

frontend/kick-covid-19/src/App.js
frontend/kick-covid-19/src/components/NavBar.js
frontend/kick-covid-19/src/pages/Login.js

can access locally with http://localhost:3000/login

feat: Add login form but not responsive to button on Nav yet

---

controllers/answer.controllers.js
controllers/post.contollers.js
controllers/user.controllers.js
frontend/kick-covid-19/src/pages/Login.js
frontend/kick-covid-19/src/pages/NewPost.js
frontend/kick-covid-19/src/pages/SignUp.js
frontend/kick-covid-19/src/pages/style.css

revised crud ops - tested on postman - all good. Also, attempt to trigger a redirect on NewPosts.js to go back to the forum on submit.

Crud ops chgs wed

---

frontend/kick-covid-19/src/pages/Posts.js

Answers to posts are now appended in the single page view. Next, will make functionality so like adding posts, people can add answers.

feat: answers to posts now appending to single view page

---

controllers/answer.controllers.js
controllers/post.contollers.js

WIP - worked with Michael & Ben to fix association btwn posts & answers. Few TODOs remaining

chore: Fix association btwn posts and answers - see notes in code

---

frontend/kick-covid-19/src/pages/Login.js
frontend/kick-covid-19/src/pages/SignUp.js
frontend/kick-covid-19/src/pages/style.css

Login & signup forms built with Tailwind -  did use an external style.css

Signup login forms v2

---

frontend/kick-covid-19/src/pages/Login.js
frontend/kick-covid-19/src/pages/SignUp.js
frontend/kick-covid-19/src/pages/style.css

also corrected Login.js and SignUp.js from class to className

feat: add padding to blog page and margin to forms

---

frontend/kick-covid-19/src/pages/Posts.js

Within single page view, user can add answers to questions. Need to add a .then() function to reroute back to the blog.

Frontend adding answers

---

frontend/kick-covid-19/src/pages/Posts.js

When a user posts an answer, it adds it automatically with a getPost function.

feat: new answers automatically refresh

---

frontend/kick-covid-19/src/components/Post.js
frontend/kick-covid-19/src/pages/Posts.js

Add margin to posts, add answers txt under each post, made "answers" in bold.

Blogstyle changes

---

frontend/kick-covid-19/src/components/Answer.js
frontend/kick-covid-19/src/components/Post.js
frontend/kick-covid-19/src/pages/Posts.js

add color to answers to better distinguish between answers and posts.

Answer component

---

controllers/post.contollers.js
frontend/kick-covid-19/src/components/Answer.js
frontend/kick-covid-19/src/components/Post.js
frontend/kick-covid-19/src/pages/Blog.js
frontend/kick-covid-19/src/pages/Posts.js

attempted to populate both posts and answers with the usernames of pre-existing users. Changed 5 files, 4 frontend and post.controllers

feat: Add usernames to posts and answers

---

frontend/kick-covid-19/package-lock.json
frontend/kick-covid-19/package.json
frontend/kick-covid-19/src/pages/Login.js
frontend/kick-covid-19/src/pages/Posts.js
server.js

install formik for forms and add auth header code for review

Authheader post

---

frontend/kick-covid-19/package-lock.json
frontend/kick-covid-19/package.json
frontend/kick-covid-19/src/App.js
frontend/kick-covid-19/src/components/Footer.js
frontend/kick-covid-19/src/components/Header.js
frontend/kick-covid-19/src/components/Team.js
frontend/kick-covid-19/src/pages/About.js
server.js

Last minute!!!!!!! Added an about us page:

About page

---

frontend/kick-covid-19/src/utils/api-client/auth.client.js

commented out auth.client.js in frontend because it was breaking Heroku.

chore: commentout authclient

---

controllers/answer.controllers.js
controllers/auth.controllers.js
controllers/post.contollers.js
frontend/kick-covid-19/src/App.js
frontend/kick-covid-19/src/components/Answer.js
frontend/kick-covid-19/src/components/Header.js
frontend/kick-covid-19/src/pages/Login.js
frontend/kick-covid-19/src/pages/NewPost.js
frontend/kick-covid-19/src/pages/Posts.js
frontend/kick-covid-19/src/pages/SignUp.js
frontend/kick-covid-19/src/utils/api-client/auth.client.js
models/answer.models.js
models/post.models.js
models/user.models.js
package.json
routes/api/answer.routes.js
routes/api/index.js
routes/api/post.routes.js
routes/auth.routes.js
routes/index.js
server.js
utils/auth.js

User auth fully functional! When you login, you will see username in the header as shown. Also, when you comment on a post, your username will show.

Working user auth

---

frontend/kick-covid-19/src/pages/SignUp.js

Fixed err that occurs when new user signs up.

feat: after signup sent to login
